apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-info
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: book-info
  template:
    metadata:
      labels:
        app: book-info
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always